### ISSUE TITLE
Error from GpChatFinder

### ISSUE THREAD

**Issue by i40west** [Robitx/gp.nvim#10]
Running GpChatFinder always throws this error:

```
Error executing vim.schedule lua callback: /Users/jeremy/.local/share/nvim/lazy/gp.nvim/lua/gp.lua:213: attempt to index local 'file' (a nil value)
```

This is on macOS. The problem is that you're using the `-Z` option to `grep`, which is Linux-specific. On BSD I believe that will fail completely (no such option) but on macOS `-Z` means to decompress files before grepping if necessary, so it doesn't error from the `grep` call but only later.

**Comment by Robitx** [comment]
@i40west Hey, thanks for the issue. I've switched to `--null` flag which should be universal (macOS, BSD, linux).

Can you confirm the last version works now on the mac?

**Comment by i40west** [comment]
It does, thanks!
