### ISSUE TITLE
I wonder which part of the code is shared to OpenAI

### ISSUE THREAD

**Issue by pgzzdiab** [Robitx/gp.nvim#113]
Hello, I want to use this plugin at work but I want to be sure that the plugin doesn't read code outside that I'm sending for request. 
Sorry if it's a dumb question.

**Comment by Robitx** [comment]
@pgzzdiab Hey, currently it sends only the code which you explicitly choose (selection/range or the stuff you put in using `:GpContext`).

In the future I'd like to add commands using LSP for generating context (if my kids won't manage to drive me completely crazy first), but these commands will be explicitly differentiated by name (slower, costlier + might share things you don't want them to).

The other relevant option is to use locally hosted models via things like ollama (https://github.com/Robitx/gp.nvim/pull/93).

**Comment by pgzzdiab** [comment]
ok, thanks for the response
