### ISSUE TITLE
GpInline, I saw in the video that there's a GpInline command~

### ISSUE THREAD

**Issue by LintaoAmons** [Robitx/gp.nvim#12]
That's a really good use case~

But it seems haven't been merged into master?

**Comment by Robitx** [comment]
@LintaoAmons Hey, `:GpInline` was removed along with `GpVisual` commands when I made a breaking change by making 
 commands supporting ranges. What used to be `GpInline` is now just `GpRewrite` run in normal/insert mode.

I suppose the naming could be better, but even the `GpInline` was just replacing the whole current line. (See https://github.com/neovim/neovim/issues/10122 and https://github.com/vim/vim/issues/3292 ).

What are your expectation from the "Inline" command - do you want something which will just write on the current cursor position while keeping the rest of the line as it was?

**Comment by LintaoAmons** [comment]
OK, I got it~ 

Oh, I'm fine, I idea about this not sure if it's a good one.

I was thinking instead of have a input after trigger cmd to ask user input their requirements, how about just let user put there question in the current editing buffer, and one shortcut to trigger the plugin to replace the current line with response. (whole buffer as context)

Like, :

```lua
-- this is current buffer
local function test()
  vim.print("haha")
end

write another function, this time print "heihei" <shortcut trigger the gp.nvim, then replace this line with the response>
```

User just continue typing in this buffer, so can change, don't afraid of making mistakes.
Because a ad-hoc input box I can only use arrow key to fix my mistakes and my poor English always makes me need to fix some words

In this way, user stay in the current buffer all the time, only one more keybinding to trigger the plugin.

**Comment by Robitx** [comment]
@LintaoAmons that's not a bad idea and is doable now :slightly_smiling_face: 

Lets have file like this:
``` py
# write add function here

def main():
    # ask user for two numbers, add them together, and print the result


if __name__ == "__main__":
    main()
```
We could call `:%GpRewrite` on it with instruction:
```
Please finish the code according to comment instructions
```

Which could be wrapped into a hook like this:
``` lua
    -- example of adding commands which implements curent buffer based on comments
    Implement = function(gp, params)
        local template = "I have the following code from {{filename}}:\n\n"
            .. "```{{filetype}}\n{{selection}}\n```\n\n"
            .. "Please respond by finishing the code above according to comment instructions."
        gp.Prompt(params, gp.Target.rewrite, nil, gp.config.command_model,
            template, gp.config.command_system_prompt)
    end,
```

So you can call `:%GpImplement` which won't ask for any instructions in the input box.

I've added this as a default hook https://github.com/Robitx/gp.nvim/commit/7adb348a4bf486966ccba446b8e5665d469aaf30 so anyone with last version can use it.

**Comment by LintaoAmons** [comment]
You must be a very good programer!

I just tried this, that's what I want!

One last question, is it possible to ask chatgpt response me only the pure code implemtation? Even without the markdown code block syntax?

```py
\`\`\`python 
# write add function here
def add(a, b):
    return a + b
\`\`\`

def main():
    # ask user for two numbers, add them together, and print the result


if __name__ == "__main__":
    main()
```

![show](https://github.com/Robitx/gp.nvim/assets/95092244/9c6739c1-11ae-41a6-af44-21d0333c52d8)

**Comment by Robitx** [comment]
@LintaoAmons Yeah the triple backticks irritate me too.

Ideally I'd like to solve it by improving the prompt instructions to the model, but they trained it to provide snippets using this ``` stuff ``` syntax and both gpt-3 and even gpt-4 are quite stubborn about it.

I might end up striping it from the response stream pragmatically.

**Comment by Robitx** [comment]
@LintaoAmons ok, try the latest version ( https://github.com/Robitx/gp.nvim/commit/219abd4574a4015cb17622d10855fc032a2627f4 ) - if the response from gpt is completely enquoted in backticks, I strip them automatically.

**Comment by LintaoAmons** [comment]
Yes, a nice workaround~

I have to add this line to the prompt to get the expected result.

![image](https://github.com/Robitx/gp.nvim/assets/95092244/469470cb-efd5-44c7-8008-84f7c0163979)

**Comment by Robitx** [comment]
@LintaoAmons yeah good catch, I use gpt-4 for all the command instruction, so I haven't notice the issue with gpt-3 which still had tendency to respond with commentary outside of the snippet.

Should be fixed in last version, I'll try to keep using gpt-3 for a while to look for more differences.
