### ISSUE TITLE
dont remove agents silently

### ISSUE THREAD

**Issue by teto** [Robitx/gp.nvim#120]
Opening a follow up of https://github.com/Robitx/gp.nvim/pull/93#issuecomment-2016846974 not to pollute the PR:
in https://github.com/Robitx/gp.nvim/blob/d76be3d067b4e7352d1e744954327982cf1d24aa/lua/gp/init.lua#L745
gp.nvim removes silently agents that dont specify `.model`  `agent.system_prompt`.

It's not possible to understand without looking at the code, I think it would be better to generate an error during startup, at minimum notify the user in checkhealth gp

**Comment by Robitx** [comment]
![image](https://github.com/user-attachments/assets/7197427e-7ede-4e03-9357-aba6c1349491)
