### ISSUE TITLE
Installation via vim-plug?

### ISSUE THREAD

**Issue by matadon** [Robitx/gp.nvim#123]
Hi there! Any instructions for installing via vim-plug[1], as this is one of the more popular plugin managers for vim/nvim?

[1] https://github.com/junegunn/vim-plug

**Comment by Robitx** [comment]
@matadon Hey, I've added the vim-plug snippet to the Readme. Plus [here](https://github.com/search?q=%2FPlug+.robitx.gp.nvim.%2F&type=code) are some examples of public configs which use gp with Plug.
