### ISSUE TITLE
How to stop stream after trigger GpResponse

### ISSUE THREAD

**Issue by LintaoAmons** [Robitx/gp.nvim#13]
Sometimes the response is too long and I already noticed the response is not what I'm looking for.

So instead of waiting for GPT to stream all the response, is it possible to just stop the process and stop the rest.

**Comment by Robitx** [comment]
@LintaoAmons Hey, I've added`:GpStop` command.

[According to openai community forum](https://community.openai.com/t/interrupting-completion-stream-in-python/30628/11) it looks like 10-20 tokens are generated on the openAI side after the stream is stopped.

**Comment by LintaoAmons** [comment]
Thank you

I must say, you've really done exactly what I'm aiming for, but I just can't pull it off yet because of my programming skills.
