### ISSUE TITLE
Open in float window

### ISSUE THREAD

**Issue by shalei6698** [Robitx/gp.nvim#14]
Thank you  for creating such a great plugin.
I have a question: Is there any method to operate in a floating window, like floatterm

**Comment by Robitx** [comment]
@shalei6698 Hey, well for single one off questions, there is a `:GpPopup`, which answers your prompt into a fresh floating window, but after you close it, it's gone.

For persistence and more complex interactions with gpt models there is a `:GpChatNew` (or `:GpChatFinder` to find and open older exchanges), both open in a normal non floating buffer.

If you describe your expectation/needs in more detail, I'll try to accommodate you. Putting a chat session into a floating window which you could hide by a command/shortcut toggling it on and off would be easy.

**Comment by shalei6698** [comment]
@Robitx Thank you, I often need to switch between code and gp buffer, such as copying text. :GpPopup is a good way to handle a single question, but I often need to continue asking questions from the previous one. Below is a simple wrapper using nui to describe my need,
```lua
M._popup_win = nil

-- leader + gp
M.toggle_float_gp = function()
  if M._popup_win ~= nil then
    if M._popup_win.winid == nil then
      M._popup_win:show()
      M._popup_win:map("n", "<C-q>", M.toggle_float_gp, { noremap = true })
    else
      M._popup_win:hide()
    end
    return
  end

  local Popup = require "nui.popup"

  M._popup_win = Popup {
    position = "50%",
    size = { width = "60%", height = "60%" },
    enter = true,
    focusable = true,
    relative = "editor",
    border = { style = "rounded" },
    buf_options = { modifiable = true, readonly = false },
  }
  M._popup_win:map("n", "<C-q>", M.toggle_float_gp, { noremap = true })
  M._popup_win:mount()
  vim.cmd "GpChatNew"
end

```
![image](https://github.com/Robitx/gp.nvim/assets/5708724/f75bf286-e142-4c23-b0c1-8c7f03f05771)

**Comment by Robitx** [comment]
@shalei6698 Try out the latest version with `:GpChatToggle` if it's to your liking.

**Comment by shalei6698** [comment]
> @shalei6698 Try out the latest version with `:GpChatToggle` if it's to your liking.

thank you, exact what i need, event restart nvim, session allways there

**Comment by skylite21** [comment]
Is it possible to toggle the chat window while the answer is being generated? For me the generation stops as soon as I close the popup with GpChatToggle

**Comment by Robitx** [comment]
@skylite21 Please try the latest version if it working as you expect.

**Comment by skylite21** [comment]
It is working flawlessly now with the float window! Thanks!
