### ISSUE TITLE
How to change the GPT model during a session

### ISSUE THREAD

**Issue by mxncr** [Robitx/gp.nvim#16]
Hi,
Thanks for the plugin, it's very nice!

I am wondering if it's possible to change the model that is used by gp.nvim during a session?
Typically, it's cheaper to make initial queries gpt-3.5 then to switch to gpt-4 if the answers are not satisfactory. 

I tried to _:lua M.config.chat_model.model = "gpt-4"_ during a session, but the result of _:GpInspectPlugin_ still contains many references to gpt-3.5. But I am not familiar with neovim plugin internals, so I don't really know what should be done.

**Comment by Robitx** [comment]
@mxncr Hey, well the chat model in the config is used for generation of each new chat session template.
```
# topic: ?

- model: {"temperature":0.7,"top_p":1,"model":"gpt-3.5-turbo-16k"}
- file: 2023-08-08_20-38-53.954.md
- role: You are a general AI assistant.

Write your queries after 🗨:. Use `<C-g><C-g>` or :GpChatRespond to generate a response.
Chats are saved automatically. To delete this chat, use `<C-g>d` or :GpChatDelete.
Be cautious of very long chats. Start a fresh chat by using `<C-g>n` or :GpChatNew.

---

🗨:

```

The `GpChatRespond` chooses the model based on the `- model: ` header, which you can edit directly by hand any time you want during the session. :slightly_smiling_face: 

I wonder if this is common enough task, that it might be worthy of automation. People could specify multiple model configurations for the chat and have some command/shortcut to cycle between them. :thinking:

**Comment by mxncr** [comment]
Yes, it's possible to change it when chatting, but I am not really using this in practice. 
By session I meant "vim session", and I would like to change the model used when calling _:GpAppend_, _:GpRewrite_, etc

It would not be necessary to change the plugin, I would be happy with writing an external lua function that changes the gp.nvim plugin state, but could you provide guidance on which variables should be changed?

**Comment by Robitx** [comment]
@mxncr `GpRewrite` etc. are using `config.command_model` so you could define a hook like 
``` lua
    CmdModelToggle = function(plugin, _)
        if plugin.__model_toggle == nil then
            plugin.__command_model1 = vim.deepcopy(plugin.config.command_model)
            plugin.__command_model2 = { model = "gpt-4", temperature = 0.7, top_p = 1 }
            plugin.__model_toggle = 2
            plugin.config.command_model = vim.deepcopy(plugin.__command_model2)
        elseif plugin.__model_toggle == 1 then
            plugin.config.command_model = vim.deepcopy(plugin.__command_model2)
            plugin.__model_toggle = 2
        else
            plugin.config.command_model = vim.deepcopy(plugin.__command_model1)
            plugin.__model_toggle = 1
        end
        print("Current model: " .. vim.inspect(plugin.config.command_model))
    end,
```

and toggle between models using `GpCmdModelToggle`. (It's not polished, I'm getting ready to bed, but should work).

**Comment by mxncr** [comment]
It's working perfectly, thank you!
