### ISSUE TITLE
How to implement a CommitStaged hook?

### ISSUE THREAD

**Issue by abereghici** [Robitx/gp.nvim#161]
I'm trying to create a hook for generating commit messages based on my staged files. Is there a way to provide the `git diff` output as a context to the agent? 
I've tried to use `vim.fn.setreg("", get_git_diff())` but doesn't seem to work.

**Comment by Robitx** [comment]
Check https://github.com/Robitx/gp.nvim/pull/145 conversation for inspiration.

**Comment by abereghici** [comment]
thank you @Robitx !
