### ISSUE TITLE
Support for Azure version of GPT

### ISSUE THREAD

**Issue by hkrutzer** [Robitx/gp.nvim#18]
Thanks for this great plugin! I am using it with the Azure version of GPT which is unfortunately different in a few subtle ways.
I had to make a simple change:

```lua
M._handle, M._pid = vim.loop.spawn("curl", {
  args = {
    "--no-buffer",
    "-s",
    "https://$URL.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2023-03-15-preview",
    "-H",
    "Content-Type: application/json",
    "-H",
    "api-key: " .. M.config.openai_api_key,
    "-d",
    vim.json.encode(payload),
  },

```

As you can see it requires a different URL and puts the model name in the URL instead of a parameter. It also uses a header called `api-key` instead of the `Authorization` header.

Would you be interested in supporting this version of GPT as well in the plugin?

**Comment by Robitx** [comment]
@hkrutzer Hey, could you try the latest version with `openai_api_endpoint` in config and confirm it works for azure?
```
	-- api endpoint (you can change this to azure endpoint)
	openai_api_endpoint = "https://api.openai.com/v1/chat/completions",
	-- openai_api_endpoint = "https://$URL.openai.azure.com/openai/deployments/{{model}}/chat/completions?api-version=2023-03-15-preview",
```

**Comment by Robitx** [comment]
@hkrutzer Please try the latest version, I've added buffering of chunks to ensure json parses only full lines.

**Comment by hkrutzer** [comment]
Thanks @Robitx it works flawlessly now.
