### ISSUE TITLE
Anthropic becomes very expensive. 

### ISSUE THREAD

**Issue by keiwanjamaly** [Robitx/gp.nvim#199]
I took a look in my anthropic console and was surprised how fast my balance is eaten by the usage of the `gp.nvim` plugin. Next thing I noticed is, that the input tokens used were extremely high. So this brings me to the conclusion, that the complete chat is bundled and sent to anthropic each time, I type `:GpChatRespond`. For smaller chats, this is not a problem but for longer chats, this gets expensive and slow very fast. 

I'm not sure, if this is fixable since I have no clue about LLMs, but maybe there should be a note somewhere, so people are not surprised by the costs.

**Comment by Robitx** [comment]
Sadly, this is normal LLM behavior, LLM doesn't remember anything, it has to go through full length of the chat every time it responds to a conversation.

The default chat template contains the line:
```lua
Be cautious of very long chats. Start a fresh chat by using `{{new_shortcut}}` or :{{cmd_prefix}}ChatNew.
```

If you can come up with better yet still short warning message, I'll change it.

Btw. https://github.com/Robitx/gp.nvim?tab=readme-ov-file#gpchatrespond-
```
Request a new GPT response for the current chat. Usin:GpChatRespond N request a new GPT response with only the last N messages as context, using everything from the end up to the Nth instance of 🗨:.. (N=1 is like asking a question in a new chat).
```

Using `:GpChatRespond N` allows you to partially combat this issue (for example if you're using chat to iteratively improve on something, you could use this to take into account only last version). Using shortcut `N<C-g><C-g>` should also work.

**Comment by keiwanjamaly** [comment]
Ahhh I have completely missed that part, my bad. I have a naughty Idea to get around the limited context window. One could summarise the LLM's response with that LLM and pass it as input to a new chat. But thank you for your response.

**Comment by qaptoR** [comment]
@keiwanjamaly another thing to do when using any AI platform (I use perplexity, claude, openai, and gemini all for different tasks) is to start a conversation with the larger model (chatgpt4o or sonnet for instance) and then as the conversation grows to between 5 and 10 messages (depending on their average lengths) switch to using the smaller model (such as chatgpt4o-mini or haiku). This tends to still give pretty good results as the context of the conversation has a good starting point for the smaller models to work from. Another approach is to just accept the smaller models as the base model for use, and only use the bigger models on highly specific queries, possibly even getting the smaller model to summarize a conversation first and feeding that into another chat window with the larger model for use as context.
