### ISSUE TITLE
`nvim_buf_add_highlight()` Causes High Memory Usage

### ISSUE THREAD

**Issue by yuukibarns** [Robitx/gp.nvim#229]
After a long chat, about 300 lines, I found the memory usage of Neovim increased significantly from 40MB to 1.2GB. System monitor shows a consistent memory increase at the rate of 4MB/s when `gp.nvim` is writing response to the buffer and after the chat ends, the memory usage won't decrease but still the highest level.
#228 fixes this.

**Comment by yuukibarns** [comment]
However, there is still a 5MB increase in memory after the commit. If further
banned gp.nvim from writing to the buffer,  the increase disappeared. 
Why such a smiple `nvim_buf_set_lines()` can cause relatively big memory usage increase?

**Comment by dreamtrail** [comment]
gp.nvim will continuously redraw the lines for streaming responses, which can be very slow for lengthy outputs. You may just disable the streaming feature , as it is a distraction anyway.

**Comment by yuukibarns** [comment]
But I do want the streaming feature, for I can stop halfway if the agent does not get the point.
