### ISSUE TITLE
.local/share/nvim/lazy/gp.nvim/lua/gp/init.lua:560: attempt to index field 'cmd' (a nil value)

### ISSUE THREAD

**Issue by isaksamsten** [Robitx/gp.nvim#25]
Hi!

Cool plugin! I'm trying to migrate here from ai.vim

But I stumble upon a few bugs:

config:

```lua
{
    "robitx/gp.nvim",
    lazy = false,
    config = function()
      require("gp").setup()

      -- or setup with your own config (see Install > Configuration in Readme)
      -- require("gp").setup(conf)

      -- shortcuts might be setup here (see Usage > Shortcuts in Readme)
    end,
  }
```

Trying to issue: `GpChatNew` results in an exception:

```
.local/share/nvim/lazy/gp.nvim/lua/gp/init.lua:560: attempt to index field 'cmd' (a nil value)
```

After that every command errors with:

```
.local/share/nvim/lazy/gp.nvim/lua/gp/init.lua:560: attempt to index field 'cmd' (a nil value)
```

I also sometimes get an error on line 884 that `config` is `nil`.

Spent some time trying to debug, but saw nothing obvious.

I'm running latest Neovim stable (0.9.2).

**Comment by Robitx** [comment]
@isaksamsten Hey, that's a nice bug.

For now, I've taken your config repo + the gp config you mentioned here and directed it against my local dev repository for gp.nvim

```
+++ b/lua/config/lazy.lua
@@ -34,4 +34,8 @@ require("lazy").setup({
       },
     },
   },
+  dev = {
+    path = "/backup/pgit/",
+    pattern = "",
+  },
 })
```

```
$cat lua/plugins/gp.lua
return {
  "robitx/gp.nvim",
  lazy = false,
  dev = true,
  config = function()
    require("gp").setup()

    -- or setup with your own config (see Install > Configuration in Readme)
    -- require("gp").setup(conf)

    -- shortcuts might be setup here (see Usage > Shortcuts in Readme)
  end,
}
``` 

And I see the same bug - something is messing with the module the module object. Adding some debug prints:
```
$git diff
diff --git a/lua/gp/init.lua b/lua/gp/init.lua
index 96a0ca1..6960c9a 100644
--- a/lua/gp/init.lua
+++ b/lua/gp/init.lua
@@ -557,6 +557,8 @@ M.setup = function(opts)
        for cmd, _ in pairs(M.cmd) do
                if M.cmd_hooks[cmd] == nil then
                        vim.api.nvim_create_user_command(M.config.cmd_prefix .. cmd, function(params)
+                               print("cmd call")
+                               print(vim.inspect(M))
                                M.cmd[cmd](params)
                        end, { nargs = "?", range = true, desc = "GPT Prompt plugin" })
                end

```
Shows that instead of plugin, there is just this:
```
cmd call
{
  _get_virt_text_chunks = <function 1>,
  hide = <function 2>,
  show = <function 3>
}
```

My own conf runs with v0.9.2 without problems. I'll try to continue debug later (after sleep and work).

**Comment by isaksamsten** [comment]
Hi!

Wow, thanks for taking the time to confirm the bug!

I figured out which of my plugins somehow affected gp. It was my own virtual text plugin that somehow interfere.

Once `better-virtual-text` is disabled, gp can start without issue. `better-virtual-text` has not caused problems with other plugins, so I'm not sure what might be wrong :-)

At least we know the cause now!

Cheers,
Isak

**Comment by isaksamsten** [comment]
The bug disappear if a set `better-virtual-text` to not load lazily (`lazy = false`). You can mark the bug as resolved and caused by my setup!

Thanks for your help, and sorry to take up your time unnecessarily.

**Comment by Robitx** [comment]
@isaksamsten No problem, you have nice neovim setup, I might steal some ideas from it for my own. :slightly_smiling_face:

**Comment by aabccd021** [comment]
In my case the bug dissapeared when i disabled [twoslash-queries.nvim](https://github.com/marilari88/twoslash-queries.nvim). Hope it helps.

**Comment by Robitx** [comment]
@aabccd021 Ok, I'm reopening this, since getting it reported by two people using two different plugins is a bit concerning.

I've extended the debug used for @isaksamsten case:
``` lua
	-- register default commands
	for cmd, _ in pairs(M.cmd) do
		if M.cmd_hooks[cmd] == nil then
			vim.api.nvim_create_user_command(M.config.cmd_prefix .. cmd, function(params)
				print("cmd call")
				print(vim.inspect(M))
				print("M:", M)
				print("require gp", require("gp"))
				print("require twoslash-queries", require("twoslash-queries"))
				-- print(M.show())
				M.cmd[cmd](params)
			end, { nargs = "?", range = true, desc = "GPT Prompt plugin" })
		end
	end
```
so calling `:GpChatNew` gives
```
cmd call
{
  attach = <function 1>,
  config = {
    highlight = "Type",
    is_enabled = false,
    multi_line = true
  },
  disable = <function 2>,
  enable = <function 3>,
  remove_queries = <function 4>,
  setup = <function 5>
}
M: table: 0x7fa2b88606d0
require gp table: 0x7fa2b85ba800
require twoslash-queries table: 0x7fa2b88606d0
```
=> when the command function registered by vim.api.nvim_create_user_command is called, instead of having reference to gp.nvim module, it sees a different one (in this instance the  twoslash-queries).

**Comment by Robitx** [comment]
Ok, with fresh eyes this was really dumb and easily fixable mistake.

All three plugins concerned here forgot to set M = {} as local variable, so they were competing over a global M (depending on what module started first).
