### ISSUE TITLE
Customize the popup(s)

### ISSUE THREAD

**Issue by isaksamsten** [Robitx/gp.nvim#27]
Hi!

A small feature request:

It would be nice to be able to customise the popup windows (different border, size etc). 

If you would accept a PR request I could potentially take a look at it.

**Comment by Robitx** [comment]
@isaksamsten Sure, I'd be glad for PR if you have time for it :slightly_smiling_face: All popups are build using this helper func https://github.com/Robitx/gp.nvim/blob/main/lua/gp/init.lua#L326C4-L326C16

It already expects a size function which allows resize if neovim window changes, styling is not parameterized yet, but that's trivial.

We just have to decide how to expose this neatly to the users.
