### ISSUE TITLE
errors when switching to another buffer during answer generation.

### ISSUE THREAD

**Issue by skylite21** [Robitx/gp.nvim#29]
When the chat window is in a tab(buffer), for example using GpChatNew, or GpChatFinder,  if I navigate to another tab during answer generation, I get the following errors:

```
Error executing vim.schedule lua callback: /home/skylite/.vim_plugged/gp.nvim/lua/gp/init.lua:824: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        /home/skylite/.vim_plugged/gp.nvim/lua/gp/init.lua:824: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
        
```

It would be great if the generation would continue in the buffer in the background.

**Comment by Robitx** [comment]
@skylite21 Thanks, can you confirm the issue disappeared in the latest version? I've tested it, but it's night and I should get some sleep.

**Comment by skylite21** [comment]
Thank you it works fine now in the updated version!
