### ISSUE TITLE
Default binds not initialized in restored gp.nvim buffers when loading a session

### ISSUE THREAD

**Issue by robstumborg** [Robitx/gp.nvim#32]
Thanks for the awesome plugin! Legitimate game changer for me.

I make heavy use of sessions in my neovim workflow. When I save a session that includes gp.nvim buffers, and then reopen that session later, the default <C-g> keybinds no longer function in those buffers, but work fine if I close and open the same file in a new buffer via the :GpChatFinder command. 

I assume this has to do with the plugin setting those binds upon creating the buffers with the :Gp commands and the finder popup, but of course I am not certain as I haven't looked at any of the code. 

This bug does not require a fix for me personally as I have set up my own binds differently than the defaults, but I figured it could be note worthy.

**Comment by Robitx** [comment]
@robstumborg Thanks for reporting this, I've moved chat setup under a BufEnter autocmd  so shortcuts, autosave etc. should work no matter how the chat file gets opened.
