### ISSUE TITLE
Transcription omits words

### ISSUE THREAD

**Issue by ro0mquy** [Robitx/gp.nvim#35]
Hey thank you for this great plugin.

Sometimes when transcribing with GpWhisper the results omits a few words. Could this be due to the trimming of silence? If so could you add an option that disables this feature?

**Comment by Robitx** [comment]
@ro0mquy Hey, words from the middle or the end? Would you be willing to send me content of `/tmp/gp_whisper` for some problematic instance?

The sox audio analysis isn't [trivial](https://ankitshah009.blogspot.com/2017/03/sox-of-silence-original-post.html), so far I've tried to hide that complexity by providing `whisper_silence` as a magic number in the config.
```
	-- multiplier of RMS level dB for threshold used by sox to detect silence vs speech
	whisper_silence = "1.75",
```

If you increase `whisper_silence` a lot (10.0 or 100.0), it should effectively disable silence trimming.
