### ISSUE TITLE
Gpt model for append

### ISSUE THREAD

**Issue by claidler** [Robitx/gp.nvim#36]
```lua
use({
		"robitx/gp.nvim",
		config = function()
			require("gp").setup({
				openai_api_key = os.getenv("OPENAI_API_KEY"),
				chat_model = "gpt-4",
				chat_topic_gen_model = "gpt-4",
				command_model = "gpt-4",
				command_system_prompt = "You are a code editor. Only return the edited code. Do not explain your response"
			})
		end,
	})
```
Firstly, great work on the plugin. Thank you.
I have this setup and I'm almost certain that the model isn't updating for prepend/append functions. Do you have any idea why? It seems to be using gpt-3 still, as far as I can tell from my open AI usage report. 
Also I set this command system prompt, as I'm finding when it attempts to append/prepend, it often adds explanatory words in, where I just want code.

**Comment by Robitx** [comment]
@claidler Hey, when you call some gp command, you can run `:GpInspectPlugin` afterwards and see among other things the raw `_payload` which was send to Open AI - do you see gpt4 there?

**Comment by claidler** [comment]
@Robitx thanks for the tip. I'm not sure if you've changed anything, but I ran PackerUpdate and it seems to be working now to update the model/config. Possibly I needed to run something to get the config to update and I wasn't aware. I'm not sure. It's done anyway. I did noticed though a separate issue FYI. 

https://github.com/Robitx/gp.nvim/assets/43636691/fc3dbb8d-4c6d-4e42-88a8-81cbd96a7e97

You see prepend is adding the current line also. Are you seeing this?

**Comment by Robitx** [comment]
@claidler Yes, you're right. I mostly use rewrite, so that append/prepend suffered a bit of negligence. :slightly_smiling_face:

I've added custom templates for append and prepend which tells the gpt to not repeat the snippet it was provided with. Try the latest version.

**Comment by claidler** [comment]
That does the trick @Robitx thanks )
