### ISSUE TITLE
Feature: add code from multiple files to chat buffer

### ISSUE THREAD

**Issue by claidler** [Robitx/gp.nvim#37]
Id really love a way to update the chat buffer with code from different files for asking questions.
For instance for a file structure:
src/ 
   - messages.js
   - chat.js

I want to be able to pick some code from messages.txt and some code from chat.txt and then ask something like "how do I add this message function to this chat class or whatever.

The way I thought this could work is:
1. Go into message.js
2. Select the relevant code
3. Call function addTextToChatBuffer
4. Go to chat.js and repeat steps 2-3.
5. Go to chat buffer and ask the question.

What do you think?

**Comment by Robitx** [comment]
Yeah, this would be useful and should be relatively easily implemented (hopefully during this weekend).

**Comment by Robitx** [comment]
@claidler Please check out the latest version with `GpChatPaste`.

**Comment by claidler** [comment]
Looks great thanks!
