### ISSUE TITLE
the video isn't available

### ISSUE THREAD

**Issue by AdrienLemaire** [Robitx/gp.nvim#38]
When clicking on the 5' video link (https://www.youtube.com/watch?v=UBc5dL1qBrc), I see 

> This video isn't available anymore

**Comment by Robitx** [comment]
@AdrienLemaire thanks. What the hell, I couldn't find any trace of the original video in my youtube studio. :slightly_frowning_face:

I've uploaded it again and switch the link in readme, but I should make new/better demo including new features etc (maybe next weekend :crossed_fingers:).
