### ISSUE TITLE
make telecope chat finder sortable by date

### ISSUE THREAD

**Issue by divramod** [Robitx/gp.nvim#43]
hey hey, thx for the awesome plugin!

is it somehow possible to sort the telescope results by date, the last first?
i use the plugin very often and cant see the logic in the sorting. 

![Screenshot 2023-11-06 at 20 37 34](https://github.com/Robitx/gp.nvim/assets/1331662/dda23939-872f-4afc-9dc5-46b2ce378ec9)

**Comment by Robitx** [comment]
@divramod hey, thanks for the report, latest version should sort this out. :slightly_smiling_face:

**Comment by divramod** [comment]
ah nice, thx!
