### ISSUE TITLE
feat: introduce convinient commands for GpChatNewVertical, GpChatNewHorizontal, GpChatNewTab

### ISSUE THREAD

**Issue by divramod** [Robitx/gp.nvim#47]
my main workflow currently is, that i select some code, and then run `<c-g>c` for GpChatNew.
after that i often go back to the original code with buffer last for having the information to explain chatgpt what i want to do.

it would be nice to have GpNewVertical, GpNewTab, GpNewHorizontal commands to be able to map `<c-g>v`, `<c-g>x`, `<c-g>t` in visual mode, so that i could open the original code buffer and the chat side by side to avoid switching back and forth between the two buffers.

i know, that i could do it somehow by myself, i did it it normal and insert mode like this

```lua
vim.keymap.set({"n", "i"}, "<C-g>x", "<cmd>split|GpChatNew<cr>",            keymapOptions("create x"))
vim.keymap.set({"n", "i"}, "<C-g>n", "<cmd>GpChatNew<cr>",                  keymapOptions("create"))
vim.keymap.set({"n", "i"}, "<C-g>t", "<cmd>tabnew|GpChatNew<cr>",           keymapOptions("create t"))
vim.keymap.set({"n", "i"}, "<C-g>v", "<cmd>vsplit|GpChatNew<cr>",           keymapOptions("create v"))
```

but i think in visual mode it is a little more complicated because i need to keep the selection?

these would be convinient commands to be able to get up and running faster for me and save a lot of time in my daily workflow.

thx again, i am so happy with that plugin!

**Comment by Robitx** [comment]
@divramod thats already implemented as part of [solution](https://github.com/Robitx/gp.nvim/commit/b5cd25f5da356b8e47e0fa6f52f34317d0a6ee88 ) for #46 => 
``` lua
vim.keymap.set({"n", "i"}, "<C-g><C-x>", "<cmd>GpChatNew split<cr>", keymapOptions("New Chat split"))
vim.keymap.set("v", "<C-g><C-x>", ":<C-u>'<,'>GpChatNew split<cr>", keymapOptions("Visual Chat New split"))
```
supported sub commands are:
![image](https://github.com/Robitx/gp.nvim/assets/8431097/ba93850a-24dd-4cba-b285-fe0f9f5ef3b3)

I just have to update the documentation and tag new release (once I also do #48)

**Comment by Robitx** [comment]
:heavy_check_mark: in the latest version

**Comment by divramod** [comment]
you are awesome! i think i might go on 🤣

**Comment by Robitx** [comment]
>  i think i might go on 🤣

@divramod feat/fix ideas are always welcome :slightly_smiling_face:
