### ISSUE TITLE
feat: configure initial search term for finder

### ISSUE THREAD

**Issue by divramod** [Robitx/gp.nvim#48]
i am currently using the finder a lot and am in the process of systematically naming my chats.
it is kind of like a diary for me and i can go back to the chats, if i have the same questions again.
really awesome stuff.

the first lines of my chats usually look like this:

```markdown
# topic: ... (original)
# [nvim] create autocmd for script
# [ts] how to ...
# [some] ...
```

the finder opens with the search term `topic`, what isn't convinient anymore for me, since i changed all the topics h1 / first lines to match my title style.

it would be nice, to be able to configure the initial search term in the setup function - which is currently topic - to something the user wants. for me it would be `# \[`.

**Comment by Robitx** [comment]
@divramod hey, try adding `chat_finder_pattern = "# \\[",` to your conf.

**Comment by divramod** [comment]
thx thx thx :-)
