### ISSUE TITLE
Insert mode lag with astronvim

### ISSUE THREAD

**Issue by teocns** [Robitx/gp.nvim#53]
I experience serious insert-mode typing lag only after the conversation was initiated and a response from GPT was generated. For reference, I use Astronvim; I have tried disabling syntax highlight and LSP - anything that comes in your mind intuitively that you consider might be causing this issue?

Note: the issue won't persist by restarting nvim and reopening the same chat buffer, but will occur after the next message.

I can confirm # topic isn't the issue.

Here's my [astronvim user config](https://github.com/teocns/astronvim), if you're willing to give it a chance. This contains the user custom configuration - you will need to setup astronvim aside, and then place this configuration under the user directory.

**Comment by Robitx** [comment]
Well running Gp with `NVIM_APPNAME=teo-nvim nvim` lead me to unrelated bufix :slightly_smiling_face:  https://github.com/Robitx/gp.nvim/commit/f0b31cd3d660084a0d9d56a6880102492641fcd6

One thing I see is `:checkhealth which-key`:
```
which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **" z"**
- rhs: ` `
```

But I made no modification to your config (besides openai_api_key) and during tests I didn't observe any lagging. Would you be willing to make a screen record of what you see on your end?

**Comment by teocns** [comment]
that slipped through, cheers! I'm not sure if it's a coincidence or not, but for now the issue does not persist anymore 🥳 will keep you updated on this in any case
