### ISSUE TITLE
idea: create dall-e request and download the generated images

### ISSUE THREAD

**Issue by divramod** [Robitx/gp.nvim#58]
i really like the newly integrated dall-e image generation in the chat and i use it a lot.

do you have an idea, if it would be possible, to call the model generating the images?

after the request finished, it would be nice to have a download image dialog, where one could choose the location.

**Comment by Robitx** [comment]
@divramod Hey, the latest version supports `:GpImage` to handle the generation flow and `:GpImageAgent`
![image](https://github.com/Robitx/gp.nvim/assets/8431097/d3858642-b495-4c0e-aeab-d09195e32c60)

**Comment by divramod** [comment]
awesome stuff! simply awesome!

**Comment by divramod** [comment]
sooo nice! 
would it be possible to configure the standard folder like with chat_dir, whisper_dir, state_dir?

**Comment by Robitx** [comment]
> btw, GpNextAgent only changes the command agent. Is this on purpose?

it changes the agent based on where you are - if you're in a chat buffer it cycles between chat agents, anywhere else it cycles between command agents

> maybe a second command like GpImageDefault?

what should it do? just as chat and command agents, the "image agent" (configuration) is persisted in state_dir across neovim instances, so it you set it for example to `DALL-E-3-1792x1024-vivid` it will be used for images until you change it.

> would it be possible to configure a default folder for the images like with chat_dir, whisper_dir, state_dir?

this should be trivial, will do before crashing to bed for some sleep
