### ISSUE TITLE
Add shortcuts under `GpChat` buffer

### ISSUE THREAD

**Issue by LintaoAmons** [Robitx/gp.nvim#6]
Right now, we binding keys globally to `Gp` commands.

If it's better to have shortcuts to trigger the `Gp` commands under `GpChat` buffer.

Like `r` in normal mode in `GpChat` to trigger `GpChatResponse`.

Something like `Neogit` did when under `NeogitStatus` buffer.

**Comment by Robitx** [comment]
Done, closing.
