### ISSUE TITLE
question: how to integrate whisper to be more productive

### ISSUE THREAD

**Issue by divramod** [Robitx/gp.nvim#68]
hey hey again,

i am just starting with the whisper functionality of gp.nvim and its awesome.
my english isn't that good, but it is recognizing nearly 100% of the words i speak.

now my question: is it currently already possible to use whisper somehow also in the gp chat windows?

i often have conversations with the api and develop the functions i need in an incremental matter.
it would be awesome to use gpwhispers speech-to-text conversion results in the chat conversation. 
i am quite fast with with writing but realized, that i am faster speaking.
to copy text to the chatwindow or adapt the text whisper wrote its still more productive to use the keyboard.
but the explanations/instructions i want to give to the chat will be inputted faster with speech.

so the optimal workflow for me would look like a combination of the possibilities of combined text and speech instructions in the chat window. 
when i am finished inputting all instructions via text and speech, i could trigger the api request in the usual manner.

i am interested in what you think the optimal/most productive/fastest way to code with gp.nvim looks like in your view.

greetings!

**Comment by Robitx** [comment]
@divramod Hey, sorry for late response (busy day job).

The plain `:GpWhisper` or (it's shortcut) should work in any buffer including the chats. It replaces the current line with the text recognized from the speech. So you can combine written/pasted text with speech and when done just run ChatRespond as normal. The rest of the whisper commands like`:GpWhisperRewrite` are equivalents of commands without the whisper (like `:GpRewrite`)

I guess I should make the Readme more clear. :slightly_smiling_face:

**Comment by divramod** [comment]
awesome! thx!
i am using it now :-)
