### ISSUE TITLE
Use password manager to get the API KEY.

### ISSUE THREAD

**Issue by OliverChao** [Robitx/gp.nvim#76]
If users use password managers like 1Password or Bitwarden, they can get the api key by running some system command.
For example `bw get password chatgpt-api-key`.
Maybe we need one new optional way to get the key.

**Comment by OliverChao** [comment]
https://github.com/Robitx/gp.nvim/pull/75 
This pr supplements methods getting `The KEY`.

**Comment by teocns** [comment]
This is what I do to read from file:
```
    local openai_api_key_src_file = io.open("~/.config/.openai", "r")
    if openai_api_key_src_file == nil then
      print "Please create a file at ~/.config/.openai with your OpenAI API key"
      return
    end
    local openai_api_key_src = openai_api_key_src_file:read("*a"):match "^%s*(.-)%s*$" -- this trims whitespace
    openai_api_key_src_file:close()
    require("gp").setup {
 chat_topic_gen_model = "gpt-4-1106-preview",
      openai_api_key = openai_api_key_src,
...
```

**Comment by OliverChao** [comment]
> @OliverChao hey, why is
> 
> ```lua
>       require("gp").setup({
>         openai_api_key = vim.fn.system({"bw", "get", "password", "chatgpt-api-key"})
>         ...
>       })
> ```
> 
> insufficient? 🙂
> 
> If it's sufficient, we should just update the docs.

@Robitx Hi, thanks for mentioning that. 
But it really very slow not owing to `vim.fn.system` or  `gp.nvim`  but `bw`.
You know that those password managers take lots of steps for secure checks.
We need more efficient way like asynchronous functions. 

https://github.com/Robitx/gp.nvim/assets/39361033/8d417e7f-d886-43b2-a932-771b7c9939dc

**Comment by OliverChao** [comment]
> This is what I do to read from file:
> 
> ```
>     local openai_api_key_src_file = io.open("~/.config/.openai", "r")
>     if openai_api_key_src_file == nil then
>       print "Please create a file at ~/.config/.openai with your OpenAI API key"
>       return
>     end
>     local openai_api_key_src = openai_api_key_src_file:read("*a"):match "^%s*(.-)%s*$" -- this trims whitespace
>     openai_api_key_src_file:close()
>     require("gp").setup {
>  chat_topic_gen_model = "gpt-4-1106-preview",
>       openai_api_key = openai_api_key_src,
> ...
> ```

Yes. Reading from one secure file is another way but somebody like me use the password manager that controls all passwords and  provides easy and secure way to get  them. 
Another words, asynchronous process seems more efficient.

**Comment by Robitx** [comment]
@OliverChao ok, I've polished the PR a little bit and [summarized the options in the readme](https://github.com/Robitx/gp.nvim#2-openai-api-key) hopefully nudging people towards more secure approaches.

Instead of adding `openai_api_key_cmd` with `openai_api_key` being empty, `openai_api_key` serves for both differentiating based on type (string => key, table of strings => command with args).
