### ISSUE TITLE
Use stdpath for chats_dir

### ISSUE THREAD

**Issue by razak17** [Robitx/gp.nvim#9]
Instead of the manual chats_dir in the default config, I think using nvim's stdpath like so, 
`chat_dir = vim.fn.stdpath('data') .. 'gp' .. 'chats'`
will be more useful for those using neovim distributions or people like me who use a separate
config directory from neovim's default one.

**Comment by Robitx** [comment]
@razak17 Hey, thanks for pointing this out - fixed and closing.
