### ISSUE TITLE
Text is highlighted whilst generated

### ISSUE THREAD

**Issue by 8veStory** [Robitx/gp.nvim#96]
Hi, I notice that during generation there is a highlight over the text, which removes the syntax highlighting. Highlighting is cleared when generation is complete. When using slower models like GPT4 or when generation takes a long time, it makes the text a little hard to read whilst it is generating.

## Examples of Highlighting
My Example (gif):
![example](https://github.com/Robitx/gp.nvim/assets/29248979/a30deba6-5d77-480e-91cc-e709093a809a)

Another Example from demo at 2:31.
https://youtu.be/X-cT7s47PLo?feature=shared&t=151

## Examples of No Highlighting
However, I noticed that from previous screencasts this did not seem to be the case?
Example (from front page):
<img src="https://github.com/Robitx/gp.nvim/assets/8431097/c538f0a2-4667-444e-8671-13f8ea261be1" width="49%">

Is the highlight intended behaviour?

**Comment by Robitx** [comment]
@8veStory Hey, highlight of generated content is intended, but not at the expense of syntax highlighting. Please try the latest version, I've tried to use "less aggressive" highlight group which should have better behavior across color schemes. What color scheme are you using? So I could test yours directly.

**Comment by 8veStory** [comment]
Thanks for the quick response! I was using the `catppuccin mocha` theme ([link](https://github.com/catppuccin/nvim)). I've updated to the latest version and it appears to be fixed; the highlight no longer covers the syntax highlighting. Thanks again!
